// Generated by scripts/build_furniture_atlas.py. Do not edit by hand.
export const FURNITURE_REFERENCE_CELL = 96 as const
export const FURNITURE_ATLAS_SIZE = { width: 4096, height: 4096 } as const
export const FURNITURE_ATLAS_FRAMES = {
  "green-armchair": [
    {
      "rect": [
        3748,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3852,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3956,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "orange-armchair": [
    {
      "rect": [
        3852,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3956,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        108,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "brown-stool": [
    {
      "rect": [
        2084,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2188,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2292,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        2396,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "green-desk-chair": [
    {
      "rect": [
        524,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        628,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        732,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        836,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "blue-desk-chair": [
    {
      "rect": [
        1252,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1356,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1460,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        1564,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "beige-desk-chair": [
    {
      "rect": [
        836,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        940,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1044,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        1148,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "narrow-nightstand": [
    {
      "rect": [
        3436,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3540,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3644,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        10,
        5,
        86,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3748,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "red-desk-chair": [
    {
      "rect": [
        1460,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1564,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1668,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        1772,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "green-side-chair": [
    {
      "rect": [
        1772,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1876,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1980,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        2084,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "plant-stand": [
    {
      "rect": [
        628,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        21,
        5,
        74,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        732,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        26,
        5,
        69,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        836,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        22,
        5,
        73,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        940,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        27,
        5,
        69,
        91
      ],
      "authored": true
    }
  ],
  "etched-cabinet": [
    {
      "rect": [
        3332,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3436,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3540,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        10,
        5,
        86,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3644,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "stone-pedestal": [
    {
      "rect": [
        3124,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        26,
        91,
        70
      ],
      "authored": true
    },
    {
      "rect": [
        3228,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        28,
        5,
        67,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3332,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        26,
        91,
        70
      ],
      "authored": true
    },
    {
      "rect": [
        3436,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        28,
        5,
        67,
        91
      ],
      "authored": true
    }
  ],
  "tall-nightstand": [
    {
      "rect": [
        3540,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3644,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3748,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        10,
        5,
        86,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3852,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "green-ottoman": [
    {
      "rect": [
        940,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1044,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1148,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        1252,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "orange-ottoman": [
    {
      "rect": [
        212,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        316,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        420,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        524,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "wooden-bench": [
    {
      "rect": [
        316,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        26,
        91,
        70
      ],
      "authored": true
    },
    {
      "rect": [
        420,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        28,
        5,
        67,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        524,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        26,
        91,
        70
      ],
      "authored": true
    },
    {
      "rect": [
        628,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        28,
        5,
        67,
        91
      ],
      "authored": true
    }
  ],
  "compact-washer": [
    {
      "rect": [
        2916,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3020,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3124,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3228,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "compact-dryer": [
    {
      "rect": [
        2500,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2604,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2708,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2812,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "utility-bin": [
    {
      "rect": [
        3956,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        108,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        212,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "green-club-chair": [
    {
      "rect": [
        108,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        212,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        316,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        420,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "beige-club-chair": [
    {
      "rect": [
        420,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        524,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        628,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        732,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "red-club-chair": [
    {
      "rect": [
        1044,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        87,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1148,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1252,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        12,
        91,
        84
      ],
      "authored": true
    },
    {
      "rect": [
        1356,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        82,
        91
      ],
      "authored": true
    }
  ],
  "small-drawer": [
    {
      "rect": [
        2708,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2812,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2916,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        10,
        5,
        86,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3020,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "medium-drawer-a": [
    {
      "rect": [
        2604,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2708,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2812,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        10,
        5,
        86,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2916,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "medium-drawer-b": [
    {
      "rect": [
        3020,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3124,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3228,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        10,
        5,
        86,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3332,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "long-drawer": [
    {
      "rect": [
        2188,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        80,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2292,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        14,
        5,
        81,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2396,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        10,
        5,
        86,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2500,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        81,
        91
      ],
      "authored": true
    }
  ],
  "short-dresser-a": [
    {
      "rect": [
        3276,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        9,
        187,
        86
      ],
      "authored": true
    },
    {
      "rect": [
        3180,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        3476,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        10,
        187,
        85
      ],
      "authored": true
    },
    {
      "rect": [
        3284,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    }
  ],
  "short-dresser-b": [
    {
      "rect": [
        3676,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        9,
        187,
        86
      ],
      "authored": true
    },
    {
      "rect": [
        3388,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        3876,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        10,
        187,
        85
      ],
      "authored": true
    },
    {
      "rect": [
        3492,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    }
  ],
  "short-green-sofa": [
    {
      "rect": [
        4,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        6,
        5,
        185,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3596,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        11,
        5,
        85,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        204,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        8,
        187,
        87
      ],
      "authored": true
    },
    {
      "rect": [
        3700,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        13,
        5,
        83,
        187
      ],
      "authored": true
    }
  ],
  "short-red-sofa": [
    {
      "rect": [
        404,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        6,
        5,
        185,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3804,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        11,
        5,
        85,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        604,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        8,
        187,
        87
      ],
      "authored": true
    },
    {
      "rect": [
        3908,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        13,
        5,
        83,
        187
      ],
      "authored": true
    }
  ],
  "short-blue-sofa": [
    {
      "rect": [
        2876,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        6,
        5,
        185,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2972,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        11,
        5,
        85,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        3076,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        8,
        187,
        87
      ],
      "authored": true
    },
    {
      "rect": [
        3076,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        13,
        5,
        83,
        187
      ],
      "authored": true
    }
  ],
  "short-sideboard": [
    {
      "rect": [
        804,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        9,
        187,
        86
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        1004,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        10,
        187,
        85
      ],
      "authored": true
    },
    {
      "rect": [
        108,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    }
  ],
  "stub-tea-table": [
    {
      "rect": [
        1604,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        12,
        5,
        180,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        420,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        89,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        1804,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        12,
        5,
        179,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        524,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        89,
        187
      ],
      "authored": true
    }
  ],
  "stub-snack-table": [
    {
      "rect": [
        1204,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        12,
        5,
        180,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        212,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        89,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        1404,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        12,
        5,
        179,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        316,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        89,
        187
      ],
      "authored": true
    }
  ],
  "drink-sideboard": [
    {
      "rect": [
        2076,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        9,
        187,
        86
      ],
      "authored": true
    },
    {
      "rect": [
        2556,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        2276,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        10,
        187,
        85
      ],
      "authored": true
    },
    {
      "rect": [
        2660,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    }
  ],
  "wide-dresser": [
    {
      "rect": [
        2404,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        9,
        187,
        86
      ],
      "authored": true
    },
    {
      "rect": [
        836,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        2604,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        5,
        10,
        187,
        85
      ],
      "authored": true
    },
    {
      "rect": [
        940,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        90,
        187
      ],
      "authored": true
    }
  ],
  "utility-counter": [
    {
      "rect": [
        2004,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        28,
        5,
        163,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        628,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        5,
        30,
        91,
        161
      ],
      "authored": true
    },
    {
      "rect": [
        2204,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        29,
        5,
        163,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        732,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        5,
        29,
        91,
        162
      ],
      "authored": true
    }
  ],
  "low-tea-table": [
    {
      "rect": [
        2476,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        12,
        5,
        180,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2764,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        89,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        2676,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ],
      "opaqueBounds": [
        12,
        5,
        179,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        2868,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ],
      "opaqueBounds": [
        6,
        5,
        89,
        187
      ],
      "authored": true
    }
  ],
  "medium-dresser-a": [
    {
      "rect": [
        300,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        13,
        5,
        275,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1132,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        30,
        91,
        257
      ],
      "authored": true
    },
    {
      "rect": [
        596,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        9,
        5,
        279,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1236,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        28,
        91,
        259
      ],
      "authored": true
    }
  ],
  "medium-green-sofa": [
    {
      "rect": [
        892,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        22,
        5,
        265,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1340,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        14,
        91,
        274
      ],
      "authored": true
    },
    {
      "rect": [
        1188,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        272,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1444,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        281
      ],
      "authored": true
    }
  ],
  "medium-red-sofa": [
    {
      "rect": [
        1484,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        22,
        5,
        265,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1548,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        14,
        91,
        274
      ],
      "authored": true
    },
    {
      "rect": [
        1780,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        272,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1652,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        281
      ],
      "authored": true
    }
  ],
  "medium-blue-sofa": [
    {
      "rect": [
        3604,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        22,
        5,
        265,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        924,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        14,
        91,
        274
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        272,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        1028,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        281
      ],
      "authored": true
    }
  ],
  "long-dresser": [
    {
      "rect": [
        1044,
        2956,
        384,
        96
      ],
      "anchor": [
        192,
        48
      ],
      "referenceSize": [
        384,
        96
      ],
      "opaqueBounds": [
        32,
        5,
        352,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3052,
        4,
        96,
        384
      ],
      "anchor": [
        48,
        192
      ],
      "referenceSize": [
        96,
        384
      ],
      "opaqueBounds": [
        5,
        62,
        91,
        322
      ],
      "authored": true
    },
    {
      "rect": [
        1436,
        2956,
        384,
        96
      ],
      "anchor": [
        192,
        48
      ],
      "referenceSize": [
        384,
        96
      ],
      "opaqueBounds": [
        38,
        5,
        346,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3156,
        4,
        96,
        384
      ],
      "anchor": [
        48,
        192
      ],
      "referenceSize": [
        96,
        384
      ],
      "opaqueBounds": [
        5,
        59,
        91,
        325
      ],
      "authored": true
    }
  ],
  "long-green-sofa": [
    {
      "rect": [
        2420,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        22,
        5,
        265,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        508,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        14,
        91,
        274
      ],
      "authored": true
    },
    {
      "rect": [
        2716,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        272,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        612,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        281
      ],
      "authored": true
    }
  ],
  "long-red-sofa": [
    {
      "rect": [
        3012,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        22,
        5,
        265,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        716,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        14,
        91,
        274
      ],
      "authored": true
    },
    {
      "rect": [
        3308,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        272,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        820,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        281
      ],
      "authored": true
    }
  ],
  "long-blue-sofa": [
    {
      "rect": [
        1828,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        22,
        5,
        265,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        300,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        14,
        91,
        274
      ],
      "authored": true
    },
    {
      "rect": [
        2124,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ],
      "opaqueBounds": [
        15,
        5,
        272,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        404,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        281
      ],
      "authored": true
    }
  ],
  "green-cabinet-corner": [
    {
      "rect": [
        2964,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        280
      ],
      "authored": true
    },
    {
      "rect": [
        3260,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        279
      ],
      "authored": true
    },
    {
      "rect": [
        3556,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        277
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        278
      ],
      "authored": true
    }
  ],
  "green-cabinet-corner-mirror": [
    {
      "rect": [
        1780,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        279
      ],
      "authored": true
    },
    {
      "rect": [
        2076,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        277
      ],
      "authored": true
    },
    {
      "rect": [
        2372,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        278
      ],
      "authored": true
    },
    {
      "rect": [
        2668,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        280
      ],
      "authored": true
    }
  ],
  "blue-cabinet-corner": [
    {
      "rect": [
        892,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        280
      ],
      "authored": true
    },
    {
      "rect": [
        1188,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        279
      ],
      "authored": true
    },
    {
      "rect": [
        1484,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        277
      ],
      "authored": true
    },
    {
      "rect": [
        1780,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        278
      ],
      "authored": true
    }
  ],
  "blue-cabinet-corner-mirror": [
    {
      "rect": [
        3708,
        588,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        279
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        277
      ],
      "authored": true
    },
    {
      "rect": [
        300,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        278
      ],
      "authored": true
    },
    {
      "rect": [
        596,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        280
      ],
      "authored": true
    }
  ],
  "red-library-corner": [
    {
      "rect": [
        2076,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        12,
        283,
        276
      ],
      "authored": true
    },
    {
      "rect": [
        2372,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        12,
        283,
        276
      ],
      "authored": true
    },
    {
      "rect": [
        2668,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        10,
        5,
        278,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2964,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        10,
        5,
        278,
        283
      ],
      "authored": true
    }
  ],
  "red-library-corner-mirror": [
    {
      "rect": [
        892,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        12,
        283,
        276
      ],
      "authored": true
    },
    {
      "rect": [
        1188,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        10,
        5,
        278,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        1484,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        10,
        5,
        278,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        1780,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        12,
        283,
        276
      ],
      "authored": true
    }
  ],
  "red-kitchen-corner": [
    {
      "rect": [
        3556,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        300,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        596,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    }
  ],
  "red-kitchen-corner-mirror": [
    {
      "rect": [
        2372,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        2668,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2964,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        3260,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    }
  ],
  "white-kitchen-corner": [
    {
      "rect": [
        1780,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        2076,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        2372,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2668,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    }
  ],
  "white-kitchen-corner-mirror": [
    {
      "rect": [
        596,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        892,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        1188,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        1484,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    }
  ],
  "mixed-kitchen-corner": [
    {
      "rect": [
        1188,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        1484,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        1780,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2076,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    }
  ],
  "mixed-kitchen-corner-mirror": [
    {
      "rect": [
        4,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        300,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        596,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        892,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    }
  ],
  "wood-t-junction": [
    {
      "rect": [
        2964,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        16,
        283,
        271
      ],
      "authored": true
    },
    {
      "rect": [
        3260,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        89,
        283,
        199
      ],
      "authored": true
    },
    {
      "rect": [
        3556,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        270
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        2660,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        90,
        283,
        198
      ],
      "authored": true
    }
  ],
  "garden-t-junction": [
    {
      "rect": [
        596,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        16,
        283,
        271
      ],
      "authored": true
    },
    {
      "rect": [
        892,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        89,
        283,
        199
      ],
      "authored": true
    },
    {
      "rect": [
        1188,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        270
      ],
      "authored": true
    },
    {
      "rect": [
        1484,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        90,
        283,
        198
      ],
      "authored": true
    }
  ],
  "kitchen-t-junction": [
    {
      "rect": [
        1484,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        1780,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        269
      ],
      "authored": true
    },
    {
      "rect": [
        2076,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2372,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        8,
        5,
        280,
        283
      ],
      "authored": true
    }
  ],
  "blue-t-junction": [
    {
      "rect": [
        3260,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        280
      ],
      "authored": true
    },
    {
      "rect": [
        3556,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        8,
        283,
        279
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        277
      ],
      "authored": true
    },
    {
      "rect": [
        300,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        10,
        283,
        278
      ],
      "authored": true
    }
  ],
  "green-sofa-alcove": [
    {
      "rect": [
        300,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        17,
        283,
        270
      ],
      "authored": true
    },
    {
      "rect": [
        596,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        20,
        5,
        267,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        892,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        19,
        283,
        268
      ],
      "authored": true
    },
    {
      "rect": [
        1188,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        22,
        5,
        266,
        283
      ],
      "authored": true
    }
  ],
  "red-sofa-alcove": [
    {
      "rect": [
        3260,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        17,
        283,
        270
      ],
      "authored": true
    },
    {
      "rect": [
        3556,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        20,
        5,
        267,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        19,
        283,
        268
      ],
      "authored": true
    },
    {
      "rect": [
        300,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        22,
        5,
        266,
        283
      ],
      "authored": true
    }
  ],
  "blue-sofa-alcove": [
    {
      "rect": [
        2076,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        17,
        283,
        270
      ],
      "authored": true
    },
    {
      "rect": [
        2372,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        20,
        5,
        267,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2668,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        19,
        283,
        268
      ],
      "authored": true
    },
    {
      "rect": [
        2964,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        22,
        5,
        266,
        283
      ],
      "authored": true
    }
  ],
  "library-alcove": [
    {
      "rect": [
        2668,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        25,
        283,
        262
      ],
      "authored": true
    },
    {
      "rect": [
        2964,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        21,
        283,
        267
      ],
      "authored": true
    },
    {
      "rect": [
        3260,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        23,
        283,
        265
      ],
      "authored": true
    },
    {
      "rect": [
        3556,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ],
      "opaqueBounds": [
        5,
        20,
        283,
        267
      ],
      "authored": true
    }
  ],
  "library-room": [
    {
      "rect": [
        2732,
        588,
        480,
        288
      ],
      "anchor": [
        240,
        144
      ],
      "referenceSize": [
        480,
        288
      ],
      "opaqueBounds": [
        31,
        5,
        448,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2460,
        4,
        288,
        480
      ],
      "anchor": [
        144,
        240
      ],
      "referenceSize": [
        288,
        480
      ],
      "opaqueBounds": [
        5,
        19,
        283,
        461
      ],
      "authored": true
    },
    {
      "rect": [
        3220,
        588,
        480,
        288
      ],
      "anchor": [
        240,
        144
      ],
      "referenceSize": [
        480,
        288
      ],
      "opaqueBounds": [
        31,
        5,
        448,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2756,
        4,
        288,
        480
      ],
      "anchor": [
        144,
        240
      ],
      "referenceSize": [
        288,
        480
      ],
      "opaqueBounds": [
        5,
        18,
        283,
        462
      ],
      "authored": true
    }
  ],
  "kitchen-room": [
    {
      "rect": [
        3260,
        4,
        576,
        288
      ],
      "anchor": [
        288,
        144
      ],
      "referenceSize": [
        576,
        288
      ],
      "opaqueBounds": [
        24,
        5,
        552,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        4,
        288,
        576
      ],
      "anchor": [
        144,
        288
      ],
      "referenceSize": [
        288,
        576
      ],
      "opaqueBounds": [
        5,
        79,
        283,
        497
      ],
      "authored": true
    },
    {
      "rect": [
        4,
        588,
        576,
        288
      ],
      "anchor": [
        288,
        144
      ],
      "referenceSize": [
        576,
        288
      ],
      "opaqueBounds": [
        71,
        5,
        504,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        300,
        4,
        288,
        576
      ],
      "anchor": [
        144,
        288
      ],
      "referenceSize": [
        288,
        576
      ],
      "opaqueBounds": [
        5,
        70,
        283,
        505
      ],
      "authored": true
    }
  ],
  "bedroom-room": [
    {
      "rect": [
        1756,
        588,
        480,
        288
      ],
      "anchor": [
        240,
        144
      ],
      "referenceSize": [
        480,
        288
      ],
      "opaqueBounds": [
        15,
        5,
        464,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        1868,
        4,
        288,
        480
      ],
      "anchor": [
        144,
        240
      ],
      "referenceSize": [
        288,
        480
      ],
      "opaqueBounds": [
        5,
        52,
        283,
        427
      ],
      "authored": true
    },
    {
      "rect": [
        2244,
        588,
        480,
        288
      ],
      "anchor": [
        240,
        144
      ],
      "referenceSize": [
        480,
        288
      ],
      "opaqueBounds": [
        48,
        5,
        431,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        2164,
        4,
        288,
        480
      ],
      "anchor": [
        144,
        240
      ],
      "referenceSize": [
        288,
        480
      ],
      "opaqueBounds": [
        5,
        30,
        283,
        449
      ],
      "authored": true
    }
  ],
  "study-room": [
    {
      "rect": [
        588,
        588,
        576,
        288
      ],
      "anchor": [
        288,
        144
      ],
      "referenceSize": [
        576,
        288
      ],
      "opaqueBounds": [
        26,
        5,
        549,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        596,
        4,
        288,
        576
      ],
      "anchor": [
        144,
        288
      ],
      "referenceSize": [
        288,
        576
      ],
      "opaqueBounds": [
        5,
        71,
        283,
        504
      ],
      "authored": true
    },
    {
      "rect": [
        1172,
        588,
        576,
        288
      ],
      "anchor": [
        288,
        144
      ],
      "referenceSize": [
        576,
        288
      ],
      "opaqueBounds": [
        37,
        5,
        538,
        283
      ],
      "authored": true
    },
    {
      "rect": [
        892,
        4,
        288,
        576
      ],
      "anchor": [
        144,
        288
      ],
      "referenceSize": [
        288,
        576
      ],
      "opaqueBounds": [
        5,
        72,
        283,
        504
      ],
      "authored": true
    }
  ],
  "stone-fireplace": [
    {
      "rect": [
        1756,
        2660,
        192,
        192
      ],
      "anchor": [
        96,
        96
      ],
      "referenceSize": [
        192,
        192
      ],
      "opaqueBounds": [
        25,
        5,
        167,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        1956,
        2660,
        192,
        192
      ],
      "anchor": [
        96,
        96
      ],
      "referenceSize": [
        192,
        192
      ],
      "opaqueBounds": [
        41,
        5,
        150,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        2156,
        2660,
        192,
        192
      ],
      "anchor": [
        96,
        96
      ],
      "referenceSize": [
        192,
        192
      ],
      "opaqueBounds": [
        19,
        5,
        173,
        187
      ],
      "authored": true
    },
    {
      "rect": [
        2356,
        2660,
        192,
        192
      ],
      "anchor": [
        96,
        96
      ],
      "referenceSize": [
        192,
        192
      ],
      "opaqueBounds": [
        41,
        5,
        150,
        187
      ],
      "authored": true
    }
  ],
  "round-rug": [
    {
      "rect": [
        2292,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        7,
        91,
        89
      ],
      "authored": true
    },
    {
      "rect": [
        2396,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        8,
        91,
        88
      ],
      "authored": true
    },
    {
      "rect": [
        2500,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        7,
        91,
        89
      ],
      "authored": true
    },
    {
      "rect": [
        2604,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        89
      ],
      "authored": true
    }
  ],
  "green-rug": [
    {
      "rect": [
        1356,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        7,
        91,
        89
      ],
      "authored": true
    },
    {
      "rect": [
        1460,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        8,
        91,
        88
      ],
      "authored": true
    },
    {
      "rect": [
        1564,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        7,
        91,
        89
      ],
      "authored": true
    },
    {
      "rect": [
        1668,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        89
      ],
      "authored": true
    }
  ],
  "red-rug": [
    {
      "rect": [
        1876,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        7,
        91,
        89
      ],
      "authored": true
    },
    {
      "rect": [
        1980,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        8,
        91,
        88
      ],
      "authored": true
    },
    {
      "rect": [
        2084,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        7,
        91,
        89
      ],
      "authored": true
    },
    {
      "rect": [
        2188,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        89
      ],
      "authored": true
    }
  ],
  "blue-rug": [
    {
      "rect": [
        1668,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        7,
        91,
        89
      ],
      "authored": true
    },
    {
      "rect": [
        1772,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        8,
        91,
        88
      ],
      "authored": true
    },
    {
      "rect": [
        1876,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        7,
        91,
        89
      ],
      "authored": true
    },
    {
      "rect": [
        1980,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        6,
        91,
        89
      ],
      "authored": true
    }
  ]
} as const
export const PET_CAGE_FRAME = {
  "rect": [
    1188,
    4,
    672,
    480
  ],
  "anchor": [
    336,
    240
  ],
  "referenceSize": [
    672,
    480
  ],
  "opaqueBounds": [
    49,
    5,
    622,
    475
  ],
  "authored": true
} as const
export const BOUNDARY_ATLAS_FRAMES = [
  [
    {
      "rect": [
        2804,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        31,
        91,
        64
      ],
      "authored": true
    },
    {
      "rect": [
        2908,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        33,
        5,
        63,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3012,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        32,
        91,
        64
      ],
      "authored": true
    },
    {
      "rect": [
        3116,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        32,
        5,
        63,
        91
      ],
      "authored": true
    }
  ],
  [
    {
      "rect": [
        3220,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        31,
        91,
        64
      ],
      "authored": true
    },
    {
      "rect": [
        3324,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        33,
        5,
        63,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3428,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        32,
        91,
        64
      ],
      "authored": true
    },
    {
      "rect": [
        3532,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        32,
        5,
        63,
        91
      ],
      "authored": true
    }
  ],
  [
    {
      "rect": [
        3636,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        31,
        91,
        64
      ],
      "authored": true
    },
    {
      "rect": [
        3740,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        33,
        5,
        63,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        3844,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        32,
        91,
        64
      ],
      "authored": true
    },
    {
      "rect": [
        3948,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        32,
        5,
        63,
        91
      ],
      "authored": true
    }
  ],
  [
    {
      "rect": [
        4,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        31,
        91,
        64
      ],
      "authored": true
    },
    {
      "rect": [
        108,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        33,
        5,
        63,
        91
      ],
      "authored": true
    },
    {
      "rect": [
        212,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        5,
        32,
        91,
        64
      ],
      "authored": true
    },
    {
      "rect": [
        316,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ],
      "opaqueBounds": [
        32,
        5,
        63,
        91
      ],
      "authored": true
    }
  ]
] as const
