// Generated by scripts/build_furniture_atlas.py. Do not edit by hand.
export const FURNITURE_REFERENCE_CELL = 96 as const
export const FURNITURE_ATLAS_SIZE = { width: 4096, height: 4096 } as const
export const FURNITURE_ATLAS_FRAMES = {
  "green-armchair": [
    {
      "rect": [
        3748,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3852,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3956,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        4,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "orange-armchair": [
    {
      "rect": [
        3852,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3956,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        4,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        108,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "brown-stool": [
    {
      "rect": [
        2084,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2188,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2292,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2396,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "green-desk-chair": [
    {
      "rect": [
        524,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        628,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        732,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        836,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "blue-desk-chair": [
    {
      "rect": [
        1252,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1356,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1460,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1564,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "beige-desk-chair": [
    {
      "rect": [
        836,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        940,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1044,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1148,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "narrow-nightstand": [
    {
      "rect": [
        3436,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3540,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3644,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3748,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "red-desk-chair": [
    {
      "rect": [
        1460,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1564,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1668,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1772,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "green-side-chair": [
    {
      "rect": [
        1772,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1876,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1980,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2084,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "plant-stand": [
    {
      "rect": [
        628,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        732,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        836,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        940,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "etched-cabinet": [
    {
      "rect": [
        3332,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3436,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3540,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3644,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "stone-pedestal": [
    {
      "rect": [
        3124,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3228,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3332,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3436,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "tall-nightstand": [
    {
      "rect": [
        3540,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3644,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3748,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3852,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "green-ottoman": [
    {
      "rect": [
        940,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1044,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1148,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1252,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "orange-ottoman": [
    {
      "rect": [
        212,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        316,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        420,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        524,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "wooden-bench": [
    {
      "rect": [
        316,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        420,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        524,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        628,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "compact-washer": [
    {
      "rect": [
        2916,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3020,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3124,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3228,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "compact-dryer": [
    {
      "rect": [
        2500,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2604,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2708,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2812,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "utility-bin": [
    {
      "rect": [
        3956,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        4,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        108,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        212,
        3676,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "green-club-chair": [
    {
      "rect": [
        108,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        212,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        316,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        420,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "beige-club-chair": [
    {
      "rect": [
        420,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        524,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        628,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        732,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "red-club-chair": [
    {
      "rect": [
        1044,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1148,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1252,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1356,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "small-drawer": [
    {
      "rect": [
        2708,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2812,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2916,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3020,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "medium-drawer-a": [
    {
      "rect": [
        2604,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2708,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2812,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2916,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "medium-drawer-b": [
    {
      "rect": [
        3020,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3124,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3228,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3332,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "long-drawer": [
    {
      "rect": [
        2188,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2292,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2396,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2500,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "short-dresser-a": [
    {
      "rect": [
        3276,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3180,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        3476,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3284,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "short-dresser-b": [
    {
      "rect": [
        3676,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3388,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        3876,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3492,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "short-green-sofa": [
    {
      "rect": [
        4,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3596,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        204,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3700,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "short-red-sofa": [
    {
      "rect": [
        404,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3804,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        604,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3908,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "short-blue-sofa": [
    {
      "rect": [
        2876,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        2972,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        3076,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        3076,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "short-sideboard": [
    {
      "rect": [
        804,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        4,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        1004,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        108,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "stub-tea-table": [
    {
      "rect": [
        1604,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        420,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        1804,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        524,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "stub-snack-table": [
    {
      "rect": [
        1204,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        212,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        1404,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        316,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "drink-sideboard": [
    {
      "rect": [
        2076,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        2556,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        2276,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        2660,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "wide-dresser": [
    {
      "rect": [
        2404,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        836,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        2604,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        940,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "utility-counter": [
    {
      "rect": [
        2004,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        628,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        2204,
        3260,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        732,
        2956,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "low-tea-table": [
    {
      "rect": [
        2476,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        2764,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    },
    {
      "rect": [
        2676,
        3156,
        192,
        96
      ],
      "anchor": [
        96,
        48
      ],
      "referenceSize": [
        192,
        96
      ]
    },
    {
      "rect": [
        2868,
        2660,
        96,
        192
      ],
      "anchor": [
        48,
        96
      ],
      "referenceSize": [
        96,
        192
      ]
    }
  ],
  "medium-dresser-a": [
    {
      "rect": [
        300,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        1132,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    },
    {
      "rect": [
        596,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        1236,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    }
  ],
  "medium-green-sofa": [
    {
      "rect": [
        892,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        1340,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    },
    {
      "rect": [
        1188,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        1444,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    }
  ],
  "medium-red-sofa": [
    {
      "rect": [
        1484,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        1548,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    },
    {
      "rect": [
        1780,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        1652,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    }
  ],
  "medium-blue-sofa": [
    {
      "rect": [
        3604,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        924,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    },
    {
      "rect": [
        4,
        3156,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        1028,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    }
  ],
  "long-dresser": [
    {
      "rect": [
        1044,
        2956,
        384,
        96
      ],
      "anchor": [
        192,
        48
      ],
      "referenceSize": [
        384,
        96
      ]
    },
    {
      "rect": [
        3052,
        4,
        96,
        384
      ],
      "anchor": [
        48,
        192
      ],
      "referenceSize": [
        96,
        384
      ]
    },
    {
      "rect": [
        1436,
        2956,
        384,
        96
      ],
      "anchor": [
        192,
        48
      ],
      "referenceSize": [
        384,
        96
      ]
    },
    {
      "rect": [
        3156,
        4,
        96,
        384
      ],
      "anchor": [
        48,
        192
      ],
      "referenceSize": [
        96,
        384
      ]
    }
  ],
  "long-green-sofa": [
    {
      "rect": [
        2420,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        508,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    },
    {
      "rect": [
        2716,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        612,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    }
  ],
  "long-red-sofa": [
    {
      "rect": [
        3012,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        716,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    },
    {
      "rect": [
        3308,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        820,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    }
  ],
  "long-blue-sofa": [
    {
      "rect": [
        1828,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        300,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    },
    {
      "rect": [
        2124,
        2956,
        288,
        96
      ],
      "anchor": [
        144,
        48
      ],
      "referenceSize": [
        288,
        96
      ]
    },
    {
      "rect": [
        404,
        2660,
        96,
        288
      ],
      "anchor": [
        48,
        144
      ],
      "referenceSize": [
        96,
        288
      ]
    }
  ],
  "green-cabinet-corner": [
    {
      "rect": [
        2964,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3260,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3556,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        4,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "green-cabinet-corner-mirror": [
    {
      "rect": [
        1780,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2076,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2372,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2668,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "blue-cabinet-corner": [
    {
      "rect": [
        892,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1188,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1484,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1780,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "blue-cabinet-corner-mirror": [
    {
      "rect": [
        3708,
        588,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        4,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        300,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        596,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "red-library-corner": [
    {
      "rect": [
        2076,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2372,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2668,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2964,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "red-library-corner-mirror": [
    {
      "rect": [
        892,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1188,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1484,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1780,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "red-kitchen-corner": [
    {
      "rect": [
        3556,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        4,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        300,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        596,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "red-kitchen-corner-mirror": [
    {
      "rect": [
        2372,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2668,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2964,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3260,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "white-kitchen-corner": [
    {
      "rect": [
        1780,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2076,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2372,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2668,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "white-kitchen-corner-mirror": [
    {
      "rect": [
        596,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        892,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1188,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1484,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "mixed-kitchen-corner": [
    {
      "rect": [
        1188,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1484,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1780,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2076,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "mixed-kitchen-corner-mirror": [
    {
      "rect": [
        4,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        300,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        596,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        892,
        1772,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "wood-t-junction": [
    {
      "rect": [
        2964,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3260,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3556,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        4,
        2660,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "garden-t-junction": [
    {
      "rect": [
        596,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        892,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1188,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1484,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "kitchen-t-junction": [
    {
      "rect": [
        1484,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1780,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2076,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2372,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "blue-t-junction": [
    {
      "rect": [
        3260,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3556,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        4,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        300,
        1180,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "green-sofa-alcove": [
    {
      "rect": [
        300,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        596,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        892,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        1188,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "red-sofa-alcove": [
    {
      "rect": [
        3260,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3556,
        2068,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        4,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        300,
        2364,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "blue-sofa-alcove": [
    {
      "rect": [
        2076,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2372,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2668,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2964,
        884,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "library-alcove": [
    {
      "rect": [
        2668,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        2964,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3260,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    },
    {
      "rect": [
        3556,
        1476,
        288,
        288
      ],
      "anchor": [
        144,
        144
      ],
      "referenceSize": [
        288,
        288
      ]
    }
  ],
  "library-room": [
    {
      "rect": [
        2732,
        588,
        480,
        288
      ],
      "anchor": [
        240,
        144
      ],
      "referenceSize": [
        480,
        288
      ]
    },
    {
      "rect": [
        2460,
        4,
        288,
        480
      ],
      "anchor": [
        144,
        240
      ],
      "referenceSize": [
        288,
        480
      ]
    },
    {
      "rect": [
        3220,
        588,
        480,
        288
      ],
      "anchor": [
        240,
        144
      ],
      "referenceSize": [
        480,
        288
      ]
    },
    {
      "rect": [
        2756,
        4,
        288,
        480
      ],
      "anchor": [
        144,
        240
      ],
      "referenceSize": [
        288,
        480
      ]
    }
  ],
  "kitchen-room": [
    {
      "rect": [
        3260,
        4,
        576,
        288
      ],
      "anchor": [
        288,
        144
      ],
      "referenceSize": [
        576,
        288
      ]
    },
    {
      "rect": [
        4,
        4,
        288,
        576
      ],
      "anchor": [
        144,
        288
      ],
      "referenceSize": [
        288,
        576
      ]
    },
    {
      "rect": [
        4,
        588,
        576,
        288
      ],
      "anchor": [
        288,
        144
      ],
      "referenceSize": [
        576,
        288
      ]
    },
    {
      "rect": [
        300,
        4,
        288,
        576
      ],
      "anchor": [
        144,
        288
      ],
      "referenceSize": [
        288,
        576
      ]
    }
  ],
  "bedroom-room": [
    {
      "rect": [
        1756,
        588,
        480,
        288
      ],
      "anchor": [
        240,
        144
      ],
      "referenceSize": [
        480,
        288
      ]
    },
    {
      "rect": [
        1868,
        4,
        288,
        480
      ],
      "anchor": [
        144,
        240
      ],
      "referenceSize": [
        288,
        480
      ]
    },
    {
      "rect": [
        2244,
        588,
        480,
        288
      ],
      "anchor": [
        240,
        144
      ],
      "referenceSize": [
        480,
        288
      ]
    },
    {
      "rect": [
        2164,
        4,
        288,
        480
      ],
      "anchor": [
        144,
        240
      ],
      "referenceSize": [
        288,
        480
      ]
    }
  ],
  "study-room": [
    {
      "rect": [
        588,
        588,
        576,
        288
      ],
      "anchor": [
        288,
        144
      ],
      "referenceSize": [
        576,
        288
      ]
    },
    {
      "rect": [
        596,
        4,
        288,
        576
      ],
      "anchor": [
        144,
        288
      ],
      "referenceSize": [
        288,
        576
      ]
    },
    {
      "rect": [
        1172,
        588,
        576,
        288
      ],
      "anchor": [
        288,
        144
      ],
      "referenceSize": [
        576,
        288
      ]
    },
    {
      "rect": [
        892,
        4,
        288,
        576
      ],
      "anchor": [
        144,
        288
      ],
      "referenceSize": [
        288,
        576
      ]
    }
  ],
  "stone-fireplace": [
    {
      "rect": [
        1756,
        2660,
        192,
        192
      ],
      "anchor": [
        96,
        96
      ],
      "referenceSize": [
        192,
        192
      ]
    },
    {
      "rect": [
        1956,
        2660,
        192,
        192
      ],
      "anchor": [
        96,
        96
      ],
      "referenceSize": [
        192,
        192
      ]
    },
    {
      "rect": [
        2156,
        2660,
        192,
        192
      ],
      "anchor": [
        96,
        96
      ],
      "referenceSize": [
        192,
        192
      ]
    },
    {
      "rect": [
        2356,
        2660,
        192,
        192
      ],
      "anchor": [
        96,
        96
      ],
      "referenceSize": [
        192,
        192
      ]
    }
  ],
  "round-rug": [
    {
      "rect": [
        2292,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2396,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2500,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2604,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "green-rug": [
    {
      "rect": [
        1356,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1460,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1564,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1668,
        3468,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "red-rug": [
    {
      "rect": [
        1876,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1980,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2084,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2188,
        3572,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  "blue-rug": [
    {
      "rect": [
        1668,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1772,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1876,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        1980,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ]
} as const
export const PET_CAGE_FRAME = {
  "rect": [
    1188,
    4,
    672,
    480
  ],
  "anchor": [
    336,
    240
  ],
  "referenceSize": [
    672,
    480
  ]
} as const
export const BOUNDARY_ATLAS_FRAMES = [
  [
    {
      "rect": [
        2804,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        2908,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3012,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3116,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  [
    {
      "rect": [
        3220,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3324,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3428,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3532,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  [
    {
      "rect": [
        3636,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3740,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3844,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        3948,
        3260,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ],
  [
    {
      "rect": [
        4,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        108,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        212,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    },
    {
      "rect": [
        316,
        3364,
        96,
        96
      ],
      "anchor": [
        48,
        48
      ],
      "referenceSize": [
        96,
        96
      ]
    }
  ]
] as const
